//
//  PostListInterfaces.swift
//  ViperTestApp1
//
//  Created by Tomokatsu Iguchi on 2018/06/24.
//  Copyright (c) 2018年 Tomokatsu Iguchi. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum PostListNavigationOption {
}

protocol PostListWireframeInterface: WireframeInterface {
    func navigate(to option: PostListNavigationOption)
}

protocol PostListViewInterface: ViewInterface {
}

protocol PostListPresenterInterface: PresenterInterface {
}

protocol PostListInteractorInterface: InteractorInterface {
}
