//
//  PostListPresenter.swift
//  ViperTestApp1
//
//  Created by Tomokatsu Iguchi on 2018/06/24.
//  Copyright (c) 2018年 Tomokatsu Iguchi. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PostListPresenter: PostListPresenterProtocol {
    weak var view: PostListViewProtocol?
    
    var interactor: PostListInteractorInputProtocol?
    
    var wireFrame: PostListWireFrameProtocol?
    
    func viewDidLoad() {
        view?.showLoading()
        interactor?.retrievePostList()
    }
    func showPostDetail(forPost post: PostModel) {
        wireFrame?.presentPostDetailScreen(from: view!, forPost: post)
    }
}

// MARK: - Extensions -

extension PostListPresenter: PostListInteractorOutputProtocol {
    func didRetrievePosts(_ posts: [PostModel]) {
        view?.hideLoading()
        view?.showPosts(with: posts)
    }
    
    func onError() {
        view?.hideLoading()
        view?.showError()
    }
    
}
